version: "3"

services:
  postgres:
    image: "postgres:14"
    container_name: "support_db"
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: "Dockerfile"
    command:
      - bash
      - -c
      - |
        python src/manage.py migrate &&
        echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin@mail.com', 'admin')" | python src/manage.py shell &&
        gunicorn src.config.wsgi:application --bind 0.0.0.0:8000
    image: "support_app"
    container_name: "support_app"
    env_file: ".env"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ".:/app/"
    ports:
      - "8000:8000"

volumes:
  pg_data: {}
