version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  check-code-quality:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install pipenv
          command: python -m pip install --upgrade pip && pip install pipenv
      - run:  
          name: Install dependencies
          command: pipenv sync --dev --system
      - run:
          name: Run linter
          command: pip run flake8 .
      - run:
          name: Check formatting
          command: pip run black --check . && pip run isort --check-only .
      - run:
          name: Check static types
          command: pip run mypy .
