version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  check-code-quality:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-packages:
          packages: flake8 black isort
      - run:
          name: Flake8 linting
          command: |
            flake8 --max-line-length=120 .
      - run:
          name: Black formatting check
          command: |
            black --check --line-length=120 .
      - run:
          name: isort formatting check
          command: |
            isort --check .

workflows:
  main:
    jobs:
      - check-code-quality