version: '2.1'

orbs:
  python: circleci/python@1.5.0

jobs:
  check-code-quality:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: --dev
          pkg-manager: pipenv
      - run:
          name: Run linter
          command: pipenv run flake8 .
      - run:
          name: Run formatters
          command: pipenv run black --check . && pipenv run isort --check-only .
      - run:
          name: Run mypy
          command: pipenv run mypy .

  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: 
          name: Deploy to AWS
          command: ssh -o StrictHostKeyChecking=no -v ubuntu@3.120.79.78
          
workflows:
  version: 2
  check-code-and-deploy:
    jobs:
      - check-code-quality
      - hold-deploy:
          type: approval
          requires:
            - check-code-quality
      - deploy:
          requires:
            - hold-deploy