version: '2.1'

orbs:
  python: circleci/python@1.5.0

jobs:
  check-code-quality:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: --dev
          pkg-manager: pipenv
      - run:
          name: Run linter
          command: pipenv run flake8 .
      - run:
          name: Run formatters
          command: pipenv run black --check . && pipenv run isort --check-only .
      - run:
          name: Run mypy
          command: pipenv run mypy .

  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e4:d3:f5:a4:83:58:42:ad:44:e0:8f:5e:e5:f5:38:8b"
      - run: ssh -o "StrictHostKeyChecking no" -v $NAME@$IP "~/support_service/scripts/deploy.sh"
          
workflows:
  version: 2
  check-code-and-deploy:
    jobs:
      - check-code-quality
      - hold-deploy:
          type: approval
          requires:
            - check-code-quality
      - deploy:
          requires:
            - hold-deploy