version: '2.1'

orbs:
  python: circleci/python@1.5.0

jobs:
  check-code-quality:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          args: black
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run black --check .
          name: Black
          
workflows:
  main:
    jobs:
      - check-code-quality