version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - python/install-packages:
          packages: flake8 black isort
      - run:
          name: Flake8 linting
          command: |
            flake8 --max-line-length=120 .
      - run:
          name: Black formatting check
          command: |
            black --check --line-length=120 .
      - run:
          name: isort formatting check
          command: |
            isort --check .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build