version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  check-code-quality:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: python -m pip install --upgrade pip && pip install pipenv
      - run:  
          name: Install dependencies
          command: pipenv sync --dev --system
      - run:
          name: Create "requirements.txt"
          command: pip freeze > requirements.txt
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run linter
          command: |
            python3 -m venv venv
            . venv/bin/activate
            flake8 .
      - run:
          name: Check formatting
          command: |
            python3 -m venv venv
            . venv/bin/activate
            black --check .
            isort --check-only . 
      - run:
          name: Check static types
          command: |
            python3 -m venv venv
            . venv/bin/activate
            mypy .

workflows:
  main:
    jobs:
      - check-code-quality