version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  check-code-quality:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: python -m pip install --upgrade pip && pip install pipenv
      - run:  
          name: Install dependencies
          command: pipenv sync --dev --system
      - run:
          name: Create "requirements.txt"
          command: pip freeze > requirements.txt
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      test:
        override:
          - flake8 ./ --max-line-length=120
      test:
        override:
          - black ./ --line-length = 120 --check
      test:
        override:
          - isort ./ --check-only
      test:
        override:
          - mypy .

workflows:
  main:
    jobs:
      - check-code-quality