# Generated by Django 4.1.5 on 2023-02-02 12:30

from django.db import migrations, models
import users.constants.roles


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("manager", "Manager"), ("user", "User")],
                default=users.constants.roles.Role["USER"],
                max_length=7,
            ),
        ),
    ]
