# Generated by Django 4.1.7 on 2023-03-02 17:22

from django.db import migrations
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()

DEFAULT_DEV_USER_DATA = {
    "email": "admin@admin.com",
    "password": "admin",
}


def create_dev_superuser(*args, **kwargs):
    """Create a new user if not exist only for DEBUG mode.
    email: admin@admin.com
    password: admin
    """
    if not settings.DEBUG:
        return
    if not User.objects.filter(email=DEFAULT_DEV_USER_DATA["email"]).exists():
        User.objects.create_superuser(**DEFAULT_DEV_USER_DATA)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_last_login_alter_user_password"),
    ]

    operations = [migrations.RunPython(create_dev_superuser)]
