# Generated by Django 4.1.7 on 2023-03-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_create_dev_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
