# Generated by Django 4.1.7 on 2023-03-08 15:06

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.UserManager()),
            ],
        ),
    ]
