# Generated by Django 4.1.5 on 2023-01-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
    ]
