# Generated by Django 4.1.7 on 2023-02-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticket_options"),
        ("comments", "0004_rename_prev_comment_id_comment_prev_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="tickets.ticket"
            ),
        ),
    ]
